-- Migration 004 — ASSORBITA IN 002
-- La colonna paid_at è stata integrata direttamente in migration 002 (AR-142).
-- Questo file è mantenuto solo per continuità numerica; non esegue alcuna operazione.
