name: Deploy to FTP

on:
  workflow_run:
    workflows:
      - Backend CI
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'release/areariservata' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 82.198.227.235
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './backend-laravel/'
          server-dir: '/domains/francescociappa.eu/public_html/areariservata/'
          exclude: |
            **/.git/**
            **/.gitignore
            **/README.md
            **/.env
            **/.env.*
            **/vendor/**
            **/tests/**
            **/storage/logs/**
            **/.editorconfig
            **/phpunit.xml
            **/phpunit.xml.dist
